/**
 * RFC 7807 - Problem Details for HTTP APIs
 * @see https://datatracker.ietf.org/doc/html/rfc7807
 */
export interface ProblemDetails {
	/**
	 * A URI reference that identifies the problem type.
	 * When dereferenced, it should provide human-readable documentation.
	 */
	type: string;

	/**
	 * A short, human-readable summary of the problem type.
	 * It should not change from occurrence to occurrence.
	 */
	title: string;

	/**
	 * The HTTP status code generated by the origin server.
	 */
	status: number;

	/**
	 * A human-readable explanation specific to this occurrence of the problem.
	 */
	detail?: string;

	/**
	 * A URI reference that identifies the specific occurrence of the problem.
	 */
	instance?: string;

	/**
	 * Extension members for additional context.
	 */
	[key: string]: unknown;
}

export interface ValidationProblemDetails extends ProblemDetails {
	errors: ValidationError[];
}

export interface ValidationError {
	field: string;
	message: string;
	code?: string;
}

export const ProblemTypes = {
	VALIDATION_ERROR: "https://api.example.com/problems/validation-error",
	NOT_FOUND: "https://api.example.com/problems/not-found",
	CONFLICT: "https://api.example.com/problems/conflict",
	UNAUTHORIZED: "https://api.example.com/problems/unauthorized",
	FORBIDDEN: "https://api.example.com/problems/forbidden",
	INTERNAL_ERROR: "https://api.example.com/problems/internal-error",
	BAD_REQUEST: "https://api.example.com/problems/bad-request",
	DOMAIN_ERROR: "https://api.example.com/problems/domain-error",
} as const;

export function createProblemDetails(
	status: number,
	title: string,
	options?: Partial<Omit<ProblemDetails, "status" | "title">>,
): ProblemDetails {
	return {
		type: (options?.type ?? ProblemTypes.INTERNAL_ERROR) as string,
		title,
		status,
		...options,
	};
}

export function createValidationProblemDetails(
	errors: ValidationError[],
	instance?: string,
): ValidationProblemDetails {
	return {
		type: ProblemTypes.VALIDATION_ERROR,
		title: "Validation Error",
		status: 400,
		detail: "One or more validation errors occurred.",
		instance,
		errors,
	};
}
